import type { Article } from '../types';

export const mockTrendingArticles: Article[] = [
  {
    source: { id: null, name: 'TechCrunch' },
    author: 'Kyle Wiggers',
    title: 'Google\'s New AI Can Generate Music from Text Prompts',
    description: 'Google has developed a new AI model called MusicLM that can generate high-fidelity music from text descriptions. The model can also be conditioned on a melody.',
    url: 'https://example.com/article1',
    urlToImage: 'https://picsum.photos/seed/google-music-ai/400/200',
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    content: null,
  },
  {
    source: { id: null, name: 'The Verge' },
    author: 'James Vincent',
    title: 'New Robotics Breakthrough Allows Robots to Learn from Videos',
    description: 'Researchers have created a new system that allows robots to learn complex tasks by watching YouTube videos, potentially accelerating the pace of robotic automation.',
    url: 'https://example.com/article2',
    urlToImage: 'https://picsum.photos/seed/robot-learning/400/200',
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    content: null,
  },
  {
    source: { id: 'wired', name: 'Wired' },
    author: 'Will Knight',
    title: 'The Unseen Potential of Large Language Models in Science',
    description: 'LLMs are not just for chatbots. Scientists are using them to accelerate research in fields from medicine to material science, uncovering patterns humans might miss.',
    url: 'https://example.com/article3',
    urlToImage: 'https://picsum.photos/seed/llm-science/400/200',
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    content: null,
  },
    {
    source: { id: null, name: 'VentureBeat' },
    author: 'Sharon Goldman',
    title: 'Why Computer Vision is a Critical Component of the Metaverse',
    description: 'As virtual worlds become more complex, advanced computer vision will be essential for creating realistic, interactive, and safe digital experiences.',
    url: 'https://example.com/article4',
    urlToImage: 'https://picsum.photos/seed/computer-vision-metaverse/400/200',
    publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    content: null,
  },
  {
    source: { id: null, name: 'Ars Technica' },
    author: 'Benj Edwards',
    title: 'OpenAI\'s DALL-E 3 Integration into ChatGPT is a Game Changer',
    description: 'The seamless integration of a powerful image generation model directly into a conversational AI marks a new era of multimodal creativity and interaction.',
    url: 'https://example.com/article5',
    urlToImage: 'https://picsum.photos/seed/dalle-3-chatgpt/400/200',
    publishedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    content: null,
  }
];

export const mockArticles: Article[] = [
    ...mockTrendingArticles,
    {
    source: { id: null, name: 'MIT Technology Review' },
    author: 'Melissa Heikkilä',
    title: 'The Ethical Dilemmas of AI-Powered Surveillance',
    description: 'As AI-driven surveillance becomes more powerful, society faces critical questions about privacy, bias, and the potential for misuse by authoritarian regimes.',
    url: 'https://example.com/article6',
    urlToImage: 'https://picsum.photos/seed/ai-surveillance-ethics/400/200',
    publishedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    content: null,
  },
  {
    source: { id: null, name: 'Gizmodo' },
    author: 'Lucas Ropek',
    title: 'Boston Dynamics\' Atlas Robot Gets an Upgrade, Can Now Do Parkour',
    description: 'The latest iteration of the humanoid robot Atlas demonstrates unprecedented agility, performing complex parkour routines that include backflips and vaults.',
    url: 'https://example.com/article7',
    urlToImage: 'https://picsum.photos/seed/atlas-robot-parkour/400/200',
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    content: null,
  },
  {
    source: { id: null, name: 'InfoWorld' },
    author: 'Martin Heller',
    title: 'Natural Language Processing: The Next Frontier in BI',
    description: 'NLP is transforming business intelligence by allowing users to query complex datasets using plain English, making data analytics more accessible than ever before.',
    url: 'https://example.com/article8',
    urlToImage: 'https://picsum.photos/seed/nlp-business-intelligence/400/200',
    publishedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    content: null,
  },
    {
    source: { id: null, name: 'IEEE Spectrum' },
    author: 'Evan Ackerman',
    title: 'How Machine Learning is Helping to Predict Volcanic Eruptions',
    description: 'Scientists are training machine learning models on seismic data and gas emissions to create early-warning systems for volcanic eruptions, potentially saving lives.',
    url: 'https://example.com/article9',
    urlToImage: 'https://picsum.photos/seed/ml-volcano-prediction/400/200',
    publishedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    content: null,
  },
    {
    source: { id: 'reuters', name: 'Reuters' },
    author: 'Stephen Nellis',
    title: 'Apple\'s Investment in On-Device AI Pays Off with New Chip',
    description: 'Apple\'s new M-series chip features a significantly more powerful Neural Engine, enabling faster and more private AI features directly on user devices.',
    url: 'https://example.com/article10',
    urlToImage: 'https://picsum.photos/seed/apple-on-device-ai/400/200',
    publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    content: null,
  },
  {
    source: { id: null, name: 'CNET' },
    author: 'Ian Sherr',
    title: 'The Role of Computer Vision in Autonomous Driving',
    description: 'A deep dive into the complex computer vision systems that allow self-driving cars to perceive and interpret the world around them, from identifying pedestrians to reading traffic signs.',
    url: 'https://example.com/article11',
    urlToImage: 'https://picsum.photos/seed/cv-autonomous-driving/400/200',
    publishedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    content: null,
  },
  {
    source: { id: null, name: 'ScienceDaily' },
    author: 'University of Cambridge',
    title: 'AI Discovers New Catalyst for More Efficient Green Hydrogen Production',
    description: 'An AI system has identified a new material that could significantly reduce the cost and increase the efficiency of producing hydrogen from water, a key goal for clean energy.',
    url: 'https://example.com/article12',
    urlToImage: 'https://picsum.photos/seed/ai-green-hydrogen/400/200',
    publishedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    content: null,
  }
];
